#!/usr/bin/env bash
# displays:
# The content of the current directory in a list format
# Where only the part of the name after the first dash is
# displayed (refer to the example)

cat /etc/passwd > filepath
filename="filepath"
while  read -r line
do
    echo "$line" | cut -d ":" -f1,3,6
done < $filename