#!/usr/bin/env bash
# display hours from 0 to 12
# display minutes from 1 to 59

i=1
j=0
while (( i<14 ))
do
	j=0
	while (( j<60 ))
		do
			echo "$j"
			j=$(( j+1 ))
		done
	if [[ $i != 13 ]]
	then
		echo "Hour: $i"
	fi
	i=$(( i+1 ))
done