#!/usr/bin/env bash
# display hours from 0 to 12
# display minutes from 1 to 59

i=0
j=0
while (( i<13 ))
do
	echo "Hour: $i"
	j=0
	while (( j<60 ))
		do
			echo "$j"
			j=$(( j+1 ))
		done
	i=$(( i+1 ))
done