#!/usr/bin/env bash
# displays:
# The content of the current directory in a list format
# Where only the part of the name after the first dash is
# displayed (refer to the example)

list="$(ls)"
for folder in $list
do
    echo "$folder" | cut -d "-" -f 2
done