#!/usr/bin/env bash
# gives information about a file if it exists and prints it
# if the file does not exist it prints file does not exists

file="holbertonschool"

if [ -e "$file" ]
then
	echo "holbertonschool file exists"
	if [ -s "$file" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "$file" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi