#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts_new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts_new
echo '8.8.8.8	facebook.com' >> ~/hosts_new
cp -f ~/hosts_new /etc/hosts
